### ISSUE TITLE
Use a RFC process to open discussion of major changes being planned.

### ISSUE THREAD

**Issue by ryanbnl** [eu-digital-green-certificates/dgca-validation-service#103]
We are currently planning major changes to the Validation Services within the confines of the Tech IOP.

This unfortunately means that only a small number of stakeholders have a chance to contribute to the process, which increases the chances of any changes being optimal.

This can be avoided by adopting a process of having open Request for Comments. This process is followed by Smart Health Card, and most other open source projects, resulting in a much better end result for everyone.

**Comment by eelcofolkertsma** [comment]
Nice concept, I love to experiment with it. Would you have some guidance how to work for some-one not very familiar with github?

**Comment by ryanbnl** [comment]
There are lots of way to do it, the key is to publish an initial specification in public in a forum where discussion can take place. Lots of projects use mailing lists, others (like SHC) use github.

I like the SHC example, they public the RFC in their git repository (https://github.com/smart-on-fhir/health-cards/tree/main/rfcs) and the discussion happens in a github issue.
